### ISSUE TITLE
Block-Breaking Bug

### ISSUE THREAD

**Issue by Mew2K** [chatasma/PGM#1]
**Issue Description**: Attempting to break any block on this map causes the error to be thrown. Any block-break the player attempts will be unsuccessful, i.e. the block will remain on the map (except, for some reason, dandelions; there may be other blocks that behave this way too). It seems block-breaking is intended to be disabled on this map except for "presents" (i.e. player heads), which means the map is unplayable as the objective cannot be accomplished.

**Map**: The Grinch's Heist of St. Carrotfields

**Video**:

https://github.com/chatasma/PGM/assets/72997300/d12771e7-28bf-4336-abf3-5bd32b2306d1

**Stack Trace**:
[17:01:14 ERROR]: Could not pass event ParticipantBlockTransformEvent to PGM v0.16-SNAPSHOT (git-28259e6)
java.lang.IllegalArgumentException: object is not an instance of declaring class
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at tc.oc.pgm.util.reflect.ReflectionUtils.callMethod(ReflectionUtils.java:39) ~[?:?]
        at tc.oc.pgm.util.nms.reflect.ReflectionProxy.lambda$callMethod$6(ReflectionProxy.java:250) ~[?:?]
        at tc.oc.pgm.util.nms.reflect.ReflectionProxy.invoke(ReflectionProxy.java:43) ~[?:?]
        at com.sun.proxy.$Proxy65.getMaterial(Unknown Source) ~[?:?]
        at tc.oc.pgm.platform.v1_13.nms.NMSHacks1_13.canMineBlock(NMSHacks1_13.java:65) ~[?:?]
        at tc.oc.pgm.util.nms.NMSHacks.canMineBlock(NMSHacks.java:325) ~[?:?]
        at tc.oc.pgm.blockdrops.BlockDropsRuleSet.getDrops(BlockDropsRuleSet.java:109) ~[?:?]
        at tc.oc.pgm.blockdrops.BlockDropsRuleSet.getDrops(BlockDropsRuleSet.java:85) ~[?:?]
        at tc.oc.pgm.blockdrops.BlockDropsMatchModule.initializeDrops(BlockDropsMatchModule.java:78) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor322.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-657]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-657]
        at tc.oc.pgm.util.bukkit.Events.callEvent(Events.java:40) ~[?:?]
        at tc.oc.pgm.listeners.BlockTransformListener$1.execute(BlockTransformListener.java:138) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:299) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:198) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1271) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-657]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-657]
        at java.lang.Thread.run(Thread.java:835) [?:?]

**Comment by chatasma** [comment]
Two issues:

* `canMineBlock` had a bad reflection call, fixed this for to utilize regular Bukkit API as in #14 
* When breaking the gift, which is a player skull, as the Grinch it didn't properly detect the break and assign the point. This is because the skull didn't drop. The skull didn't drop because the `point-blocks` filter denied drops. The `point-blocks` filter is a filter utilized by the block drops module, allowing any drop resembling the `skull` material (as defined in the XML) to be dropped. Issue is `skull` is now ambiguous in 1.20. Changed this so specifying `skull` yields its own specialized MaterialData, defining its own similar material set to the set of skull heads (i.e. wither skulls, creeper/piglin heads, player heads). Now the material data yielded by the XML-defined and the material data yielded from the broken block when compared successfully match with one another allowing the drop now.
