### ISSUE TITLE
EntityDamageByEntityEvent Bug

### ISSUE THREAD

**Issue by Mew2K** [chatasma/PGM#10]
**Issue Description**: Removing an item from an item-frame by left-clicking on it, shooting an arrow at it, or causing a creeper explosion will output this error (or a similar variation) to the console. Tnt explosions do not cause this error to be thrown (tnt is utilized on this map as an item in the kits system). The item in the item-frame will drop and can be picked up when broken in all cases (however, in PGM 1.8, it seems intended for this object to drop as an item when broken with tnt).

**Map**: MobArena: Silent City

**Stack Trace**:
[12:38:26 ERROR]: Could not pass event EntityDamageByEntityEvent to PGM v0.16-SNAPSHOT (git-28259e6)
java.lang.IllegalArgumentException: Material must be a block!
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockState.setType(CraftBlockState.java:126) ~[patched_1.13.2.jar:git-Paper-657]
        at tc.oc.pgm.platform.v1_13.material.MaterialData1_13.apply(MaterialData1_13.java:134) ~[?:?]
        at tc.oc.pgm.util.block.BlockStates.cloneWithMaterial(BlockStates.java:26) ~[?:?]
        at tc.oc.pgm.regions.RegionMatchModule.getHangingBlockState(RegionMatchModule.java:412) ~[?:?]
        at tc.oc.pgm.regions.RegionMatchModule.handleHangingBreak(RegionMatchModule.java:365) ~[?:?]
        at tc.oc.pgm.regions.RegionMatchModule.checkItemFrameItemRemove(RegionMatchModule.java:299) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor231.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-657]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:104) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:834) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:733) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:885) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.EntityItemFrame.damageEntity(EntityItemFrame.java:99) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.EntityArrow.b(EntityArrow.java:341) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.EntityArrow.a(EntityArrow.java:284) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.EntityArrow.tick(EntityArrow.java:209) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.EntityTippedArrow.tick(EntityTippedArrow.java:85) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1561) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.World.g(World.java:1528) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1339) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:599) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1107) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-657]
        at java.lang.Thread.run(Thread.java:835) [?:?]

**Comment by chatasma** [comment]
It looks like PGM tries to regulate rotating/breaking/removing the item from/placing item frames by respecting block break/place filters specified by apply elements on the region. But, it seems like it fails to generate the block query to pass to the region filter though because when determining the block state to use for the query it gets the block state at the current block (which is a block state associated with AIR, as item frames are not blocks) and tries setting the type ID & block data. The [newer implementation of setting the type on a BlockState in CraftBukkit now checks to make sure you set the type to a valid block](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/5184216f2788fb1bd722dfe1ac53ee2f4c2f4177#src%2Fmain%2Fjava%2Forg%2Fbukkit%2Fcraftbukkit%2Fblock%2FCraftBlockState.java) (as it probably should). So that's why the error pops up. But, considering item frames were never blocks to begin with I'm not really sure why this was implemented this way to begin with, it would make more sense to implement the query as an entity query or something? Practically speaking I don't think there are any entity filters even defined on regions so the event associated with the query has its cancellation status untouched. TLDR I'm going to refactor these item frame handlers to submit an entity query to avoid generating this block state altogether.

**Comment by chatasma** [comment]
Changed this to just use the original BlockState, which is not really right but gets rid of the error for now
