### ISSUE TITLE
AsyncPlayerChatEvent Bug

### ISSUE THREAD

**Issue by Mew2K** [chatasma/PGM#13]
**Issue Description**: Attempting to send a chat message causes this warning to appear in the console, and the chat message does not end up being sent.

**Version**: [PGM-0.16-SNAPSHOT-8998d10d.jar](https://cdn.discordapp.com/attachments/810660676938235964/1241288190837395508/PGM-0.16-SNAPSHOT-8998d10d.jar?ex=664ba176&is=664a4ff6&hm=a0292c44ad3133b98b74850f2d95743bd01969441304a68d0ce4d4e106132b47&)

**Stack Trace**:
[22:30:39 WARN]: java.lang.IllegalStateException: AsyncPlayerChatEvent may only be triggered synchronously.
[22:30:39 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:42)
[22:30:39 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[22:30:39 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[22:30:39 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//tc.oc.pgm.match.MatchImpl.callEvent(MatchImpl.java:247)
[22:30:39 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//tc.oc.pgm.listeners.ChatDispatcher.asyncSendChat(ChatDispatcher.java:376)
[22:30:39 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//tc.oc.pgm.listeners.ChatDispatcher.lambda$send$7(ChatDispatcher.java:361)
[22:30:39 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[22:30:39 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//tc.oc.pgm.util.concurrent.TaskExecutorService$Task.run(TaskExecutorService.java:228)
[22:30:39 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[22:30:39 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:30:39 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:30:39 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[22:30:39 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[22:30:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by chatasma** [comment]
From what I can tell PGM just did not mark the chat events as async despite them being fired as async, so just updated the chat events to set the async flag to true
