### ISSUE TITLE
Class not found for interface tc.oc.pgm.util.nms.reflect.Refl$Block

### ISSUE THREAD

**Issue by Mew2K** [chatasma/PGM#14]
**Issue Description**: On some maps, attempting to break any block causes this error to be thrown to the console. The block still breaks successfully though, and there does not seem to be any discernable gameplay hinderance. However, I have not been able to determine a pattern as to why certain maps have this error while others do not.

**Version**: [PGM-0.16-SNAPSHOT-8998d10d.jar](https://cdn.discordapp.com/attachments/810660676938235964/1241288190837395508/PGM-0.16-SNAPSHOT-8998d10d.jar?ex=664ba176&is=664a4ff6&hm=a0292c44ad3133b98b74850f2d95743bd01969441304a68d0ce4d4e106132b47&)

**Maps (Bug does occur)**: Race for Victory 3, Warlock, Bloody Trident

**Maps (Bug does not occur)**: Azonarr, Airship Battles, Deepwind Redux DTC, Balloons DTM

**Stack Trace**:
[22:53:54 ERROR]: Could not pass event ParticipantBlockTransformEvent to PGM v0.16-SNAPSHOT (git-9a60b930)
java.lang.RuntimeException: Class not found for interface tc.oc.pgm.util.nms.reflect.Refl$Block
        at tc.oc.pgm.util.nms.reflect.ReflectionProxy.getAnnotatedClass(ReflectionProxy.java:320) ~[PGM-0.16-SNAPSHOT-8998d10d.jar:?]
        at tc.oc.pgm.util.nms.reflect.ReflectionProxy.lambda$invoke$0(ReflectionProxy.java:36) ~[PGM-0.16-SNAPSHOT-8998d10d.jar:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740) ~[?:?]
        at tc.oc.pgm.util.nms.reflect.ReflectionProxy.invoke(ReflectionProxy.java:32) ~[PGM-0.16-SNAPSHOT-8998d10d.jar:?]
        at jdk.proxy4.$Proxy102.getBlockData(Unknown Source) ~[PGM-0.16-SNAPSHOT-8998d10d.jar:?]
        at tc.oc.pgm.platform.v1_20.nms.NMSHacks1_20.canMineBlock(NMSHacks1_20.java:87) ~[PGM-0.16-SNAPSHOT-8998d10d.jar:?]
        at tc.oc.pgm.util.nms.NMSHacks.canMineBlock(NMSHacks.java:330) ~[PGM-0.16-SNAPSHOT-8998d10d.jar:?]
        at tc.oc.pgm.blockdrops.BlockDropsRuleSet.getDrops(BlockDropsRuleSet.java:109) ~[PGM-0.16-SNAPSHOT-8998d10d.jar:?]
        at tc.oc.pgm.blockdrops.BlockDropsRuleSet.getDrops(BlockDropsRuleSet.java:85) ~[PGM-0.16-SNAPSHOT-8998d10d.jar:?]
        at tc.oc.pgm.blockdrops.BlockDropsMatchModule.initializeDrops(BlockDropsMatchModule.java:78) ~[PGM-0.16-SNAPSHOT-8998d10d.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor357.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-496]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at tc.oc.pgm.util.bukkit.Events.callEvent(Events.java:40) ~[PGM-0.16-SNAPSHOT-8998d10d.jar:?]
        at tc.oc.pgm.listeners.BlockTransformListener$1.execute(BlockTransformListener.java:138) ~[PGM-0.16-SNAPSHOT-8998d10d.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-496]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-496]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:375) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:334) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:298) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1847) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1343) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by chatasma** [comment]
Fixed this as part of #1 , bad reflection call in canMineBlock that I changed to use standard API
