### ISSUE TITLE
FieldAccessException Bug

### ISSUE THREAD

**Issue by Mew2K** [chatasma/PGM#15]
**Issue Description**: Picking up a flag objective causes this warning to be thrown in the console. There does not seem to be any noticeable problems that arise afterwards in terms of gameplay. 

**Map**: A SpOOky Sunset II

**Version**: [PGM-0.16-SNAPSHOT-8998d10d.jar](https://cdn.discordapp.com/attachments/810660676938235964/1241288190837395508/PGM-0.16-SNAPSHOT-8998d10d.jar?ex=664ba176&is=664a4ff6&hm=a0292c44ad3133b98b74850f2d95743bd01969441304a68d0ce4d4e106132b47&)

**Stack Trace**:
[18:33:54 WARN]: FieldAccessException: Field index 0 is out of bounds for length 0
[18:33:54 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49)
[18:33:54 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:315)
[18:33:54 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//tc.oc.pgm.util.nms.v1_9.NMSHacks1_9.sendLegacyWearing(NMSHacks1_9.java:392)
[18:33:54 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//tc.oc.pgm.util.nms.NMSHacks.sendLegacyWearing(NMSHacks.java:103)
[18:33:54 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//tc.oc.pgm.flag.state.Carried.lambda$enterState$1(Carried.java:118)
[18:33:54 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[18:33:54 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//tc.oc.pgm.util.concurrent.TaskExecutorService$Task.run(TaskExecutorService.java:228)
[18:33:54 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[18:33:54 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[18:33:54 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1646)
[18:33:54 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[18:33:54 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1525)
[18:33:54 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1226)
[18:33:54 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[18:33:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by chatasma** [comment]
This seems to be an issue with trying to send a packet to legacy (<= 1.7) players to set the flag in the helmet slot. I've refactored it to just be a no-op which removes the error, mostly because if the packet structure has changed meaningfully in anyway there's not much that can be done (aside from trying to replicate the 1.7 packet definition?). In any case it seems like something the ViaVersion plugin should be responsible for anyway rather than PGM having to do this.
