### ISSUE TITLE
Firework Particle Bug

### ISSUE THREAD

**Issue by Mew2K** [chatasma/PGM#16]
**Issue Description**: Damaging a monument objective on this map causes this warning to be thrown to the console. Based on the contents of the stack trace and the two example videos below, I feel confident in saying this is caused by a discrepancy between the firework explosion particle effect for breaking a monument block on this particular map. It seems the firework spawned from breaking a monument block was intended to immediately explode, but instead takes about a second to do so in the 1.20.4 version. No other gameplay/functional elements appear to be impacted.

**Map**: Bamboo Valley III

**Version**: [PGM-0.16-SNAPSHOT-8998d10d.jar](https://cdn.discordapp.com/attachments/810660676938235964/1241288190837395508/PGM-0.16-SNAPSHOT-8998d10d.jar?ex=664ba176&is=664a4ff6&hm=a0292c44ad3133b98b74850f2d95743bd01969441304a68d0ce4d4e106132b47&)

**Video 1.8 (shows the firework particle immediately exploding upon breaking a monument block)** :

https://github.com/chatasma/PGM/assets/72997300/0411b3f3-ffc8-4448-afdb-a3d212ad4c02

**Video 1.20.4 (firework does not immediately explode, rather it travels upwards for about a second before exploding)**:

https://github.com/chatasma/PGM/assets/72997300/b15b9dae-7bb6-4ffe-b185-39946ec239f7

**Stack Trace**:
[18:45:29 WARN]: java.lang.IllegalArgumentException: java.lang.ClassCastException@158ff75b
[18:45:29 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor142.invoke(Unknown Source)
[18:45:29 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:45:29 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[18:45:29 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//io.github.bananapuncher714.nbteditor.NBTEditor.setTag(NBTEditor.java:1267)
[18:45:29 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//io.github.bananapuncher714.nbteditor.NBTEditor.setEntityTag(NBTEditor.java:644)
[18:45:29 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//io.github.bananapuncher714.nbteditor.NBTEditor.set(NBTEditor.java:1154)
[18:45:29 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//tc.oc.pgm.util.nms.v1_9.NMSHacks1_9.skipFireworksLaunch(NMSHacks1_9.java:318)
[18:45:29 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//tc.oc.pgm.util.nms.NMSHacks.skipFireworksLaunch(NMSHacks.java:74)
[18:45:29 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//tc.oc.pgm.destroyable.Destroyable.handleBlockChange(Destroyable.java:378)
[18:45:29 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//tc.oc.pgm.destroyable.DestroyableMatchModule.handleBlockChange(DestroyableMatchModule.java:99)
[18:45:29 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor381.execute(Unknown Source)
[18:45:29 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[18:45:29 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[18:45:29 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:45:29 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//tc.oc.pgm.util.bukkit.Events.callEvent(Events.java:40)
[18:45:29 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//tc.oc.pgm.listeners.BlockTransformListener$1.execute(BlockTransformListener.java:138)
[18:45:29 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[18:45:29 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:45:29 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[18:45:29 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[18:45:29 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[18:45:29 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:375)
[18:45:29 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:334)
[18:45:29 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:210)
[18:45:29 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1847)
[18:45:29 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:42)
[18:45:29 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:15)
[18:45:29 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:54)
[18:45:29 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[18:45:29 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:149)
[18:45:29 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[18:45:29 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1465)
[18:45:29 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[18:45:29 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:123)
[18:45:29 WARN]:        at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1442)
[18:45:29 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1365)
[18:45:29 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:133)
[18:45:29 WARN]:        at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1343)
[18:45:29 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1232)
[18:45:29 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[18:45:29 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[18:45:29 WARN]: java.lang.IllegalArgumentException: java.lang.ClassCastException@47752d8f
[18:45:29 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor142.invoke(Unknown Source)
[18:45:29 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:45:29 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[18:45:29 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//io.github.bananapuncher714.nbteditor.NBTEditor.setTag(NBTEditor.java:1267)
[18:45:29 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//io.github.bananapuncher714.nbteditor.NBTEditor.setEntityTag(NBTEditor.java:644)
[18:45:29 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//io.github.bananapuncher714.nbteditor.NBTEditor.set(NBTEditor.java:1154)
[18:45:29 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//tc.oc.pgm.util.nms.v1_9.NMSHacks1_9.skipFireworksLaunch(NMSHacks1_9.java:319)
[18:45:29 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//tc.oc.pgm.util.nms.NMSHacks.skipFireworksLaunch(NMSHacks.java:74)
[18:45:29 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//tc.oc.pgm.destroyable.Destroyable.handleBlockChange(Destroyable.java:378)
[18:45:29 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//tc.oc.pgm.destroyable.DestroyableMatchModule.handleBlockChange(DestroyableMatchModule.java:99)
[18:45:29 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor381.execute(Unknown Source)
[18:45:29 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[18:45:29 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[18:45:29 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:45:29 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//tc.oc.pgm.util.bukkit.Events.callEvent(Events.java:40)
[18:45:29 WARN]:        at PGM-0.16-SNAPSHOT-8998d10d.jar//tc.oc.pgm.listeners.BlockTransformListener$1.execute(BlockTransformListener.java:138)
[18:45:29 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[18:45:29 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:45:29 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[18:45:29 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[18:45:29 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[18:45:29 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:375)
[18:45:29 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:334)
[18:45:29 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:210)
[18:45:29 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1847)
[18:45:29 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:42)
[18:45:29 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:15)
[18:45:29 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:54)
[18:45:29 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[18:45:29 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:149)
[18:45:29 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[18:45:29 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1465)
[18:45:29 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[18:45:29 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:123)
[18:45:29 WARN]:        at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1442)
[18:45:29 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1365)
[18:45:29 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:133)
[18:45:29 WARN]:        at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1343)
[18:45:29 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1232)
[18:45:29 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[18:45:29 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by chatasma** [comment]
Fixed as part of #7
