### ISSUE TITLE
EntityExplodeEvent Bug

### ISSUE THREAD

**Issue by Mew2K** [chatasma/PGM#18]
**Issue Description**: Blowing up tnt on this map causes this error to be thrown to the console. The resulting behavior of the tnt seems to be unpredictable, but it is clear that the tnt does not behave as intended.

**Map**: cos^2(tnt)

**Version**: PGM-0.16-SNAPSHOT-3c8fd1f9.jar

**Video**:

https://github.com/chatasma/PGM/assets/72997300/74de0475-917b-4bfb-89f1-1908b46db8e2

**Stack Trace**:
[14:23:32 ERROR]: Could not pass event EntityExplodeEvent to PGM v0.16-SNAPSHOT (git-9a60b930)
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.FallingBlock.setDropItem(boolean)" because "fallingBlock" is null
        at tc.oc.pgm.blockdrops.BlockDropsMatchModule.doBlockDrops(BlockDropsMatchModule.java:181) ~[PGM-0.16-SNAPSHOT-3c8fd1f9.jar:?]
        at tc.oc.pgm.listeners.BlockTransformListener.processBlockDrops(BlockTransformListener.java:578) ~[PGM-0.16-SNAPSHOT-3c8fd1f9.jar:?]
        at tc.oc.pgm.listeners.BlockTransformListener.finishCauseEvent(BlockTransformListener.java:172) ~[PGM-0.16-SNAPSHOT-3c8fd1f9.jar:?]
        at tc.oc.pgm.listeners.BlockTransformListener$1.execute(BlockTransformListener.java:147) ~[PGM-0.16-SNAPSHOT-3c8fd1f9.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-496]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-496]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.Explosion.finalizeExplosion(Explosion.java:701) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.world.level.Level.explode(Level.java:1407) ~[?:?]
        at net.minecraft.server.level.ServerLevel.explode(ServerLevel.java:1939) ~[?:?]
        at net.minecraft.world.level.Level.explode(Level.java:1365) ~[?:?]
        at net.minecraft.world.entity.item.PrimedTnt.explode(PrimedTnt.java:139) ~[?:?]
        at net.minecraft.world.entity.item.PrimedTnt.tick(PrimedTnt.java:99) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1409) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1318) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:916) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:896) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by chatasma** [comment]
The falling block that is spawned is delegated to the platform module, the 1.20 implementation was incorrectly not returning the spawned falling block, just had to make it return the block
