### ISSUE TITLE
BlockPistonExtendEvent Error

### ISSUE THREAD

**Issue by Mew2K** [chatasma/PGM#6]
**Issue Description**: Simply loading this map causes this error to be spammed to the console. 

**Map**: Fall Guys

**Stack Trace**:
[11:38:25 ERROR]: Could not pass event BlockPistonExtendEvent to PGM v0.16-SNAPSHOT (git-28259e6)
org.bukkit.event.EventException: null
        at tc.oc.pgm.listeners.BlockTransformListener$1.execute(BlockTransformListener.java:124) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.BlockPiston.a(BlockPiston.java:332) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.BlockPiston.a(BlockPiston.java:188) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.IBlockData.a(IBlockData.java:204) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.WorldServer.a(WorldServer.java:1140) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.WorldServer.an(WorldServer.java:1129) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:318) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1091) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-657]
        at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.lang.NoSuchFieldError: PISTON_EXTENSION
        at tc.oc.pgm.listeners.BlockTransformListener.onBlockPistonExtend(BlockTransformListener.java:474) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor145.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at tc.oc.pgm.listeners.BlockTransformListener$1.execute(BlockTransformListener.java:122) ~[?:?]
        ... 14 more

**Comment by chatasma** [comment]
In 1.20, it looks like it wasn't able to create piston material data from `Material.PISTON_HEAD`.. I changed this to create the material data from the source piston block and seems to have fixed this
