### ISSUE TITLE
ParticipantBlockTransformEvent Bug

### ISSUE THREAD

**Issue by Mew2K** [chatasma/PGM#7]
**Issue Description**: On this map, it appears the goal, as the map-name implies, is to "not press the button." In this case, the "button" is a block of endstone, and breaking that piece of endstone seems to be intended to indicate that the button has been pressed. However, when this block of endstone is broken, the warnings and errors below are outputted to the console, and nothing actually happens in-game (i.e. the map is unwinnable).

**Map**: Do Not Press the Button for Two Minutes

**Video**:

https://github.com/chatasma/PGM/assets/72997300/13fff990-9d39-4b16-aaf8-10ff99c248f3

**Stack Trace**:
[11:47:15 WARN]: java.lang.IllegalArgumentException: object is not an instance of declaring class
[11:47:15 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:47:15 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:47:15 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:47:15 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[11:47:15 WARN]:        at io.github.bananapuncher714.nbteditor.NBTEditor.setTag(NBTEditor.java:1363)
[11:47:15 WARN]:        at io.github.bananapuncher714.nbteditor.NBTEditor.setEntityTag(NBTEditor.java:758)
[11:47:15 WARN]:        at io.github.bananapuncher714.nbteditor.NBTEditor.set(NBTEditor.java:1250)
[11:47:15 WARN]:        at tc.oc.pgm.util.nms.v1_9.NMSHacks1_9.skipFireworksLaunch(NMSHacks1_9.java:316)
[11:47:15 WARN]:        at tc.oc.pgm.util.nms.NMSHacks.skipFireworksLaunch(NMSHacks.java:77)
[11:47:15 WARN]:        at tc.oc.pgm.destroyable.Destroyable.handleBlockChange(Destroyable.java:378)
[11:47:15 WARN]:        at tc.oc.pgm.destroyable.DestroyableMatchModule.handleBlockChange(DestroyableMatchModule.java:99)
[11:47:15 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor384.execute(Unknown Source)
[11:47:15 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[11:47:15 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[11:47:15 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
[11:47:15 WARN]:        at tc.oc.pgm.util.bukkit.Events.callEvent(Events.java:40)
[11:47:15 WARN]:        at tc.oc.pgm.listeners.BlockTransformListener$1.execute(BlockTransformListener.java:138)
[11:47:15 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[11:47:15 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
[11:47:15 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520)
[11:47:15 WARN]:        at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:299)
[11:47:15 WARN]:        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:226)
[11:47:15 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1285)
[11:47:15 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40)
[11:47:15 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10)
[11:47:15 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
[11:47:15 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[11:47:15 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[11:47:15 WARN]:        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
[11:47:15 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018)
[11:47:15 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[11:47:15 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[11:47:15 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[11:47:15 WARN]:        at java.base/java.lang.Thread.run(Thread.java:835)
[11:47:15 WARN]: java.lang.IllegalArgumentException: object is not an instance of declaring class
[11:47:15 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:47:15 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:47:15 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:47:15 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[11:47:15 WARN]:        at io.github.bananapuncher714.nbteditor.NBTEditor.setTag(NBTEditor.java:1363)
[11:47:15 WARN]:        at io.github.bananapuncher714.nbteditor.NBTEditor.setEntityTag(NBTEditor.java:758)
[11:47:15 WARN]:        at io.github.bananapuncher714.nbteditor.NBTEditor.set(NBTEditor.java:1250)
[11:47:15 WARN]:        at tc.oc.pgm.util.nms.v1_9.NMSHacks1_9.skipFireworksLaunch(NMSHacks1_9.java:317)
[11:47:15 WARN]:        at tc.oc.pgm.util.nms.NMSHacks.skipFireworksLaunch(NMSHacks.java:77)
[11:47:15 WARN]:        at tc.oc.pgm.destroyable.Destroyable.handleBlockChange(Destroyable.java:378)
[11:47:15 WARN]:        at tc.oc.pgm.destroyable.DestroyableMatchModule.handleBlockChange(DestroyableMatchModule.java:99)
[11:47:15 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor384.execute(Unknown Source)
[11:47:15 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[11:47:15 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[11:47:15 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
[11:47:15 WARN]:        at tc.oc.pgm.util.bukkit.Events.callEvent(Events.java:40)
[11:47:15 WARN]:        at tc.oc.pgm.listeners.BlockTransformListener$1.execute(BlockTransformListener.java:138)
[11:47:15 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[11:47:15 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
[11:47:15 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520)
[11:47:15 WARN]:        at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:299)
[11:47:15 WARN]:        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:226)
[11:47:15 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1285)
[11:47:15 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40)
[11:47:15 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10)
[11:47:15 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
[11:47:15 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[11:47:15 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[11:47:15 WARN]:        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
[11:47:15 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018)
[11:47:15 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[11:47:15 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[11:47:15 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[11:47:15 WARN]:        at java.base/java.lang.Thread.run(Thread.java:835)
[11:47:15 ERROR]: Could not pass event ParticipantBlockTransformEvent to PGM v0.16-SNAPSHOT (git-28259e6)
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
        at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:315) ~[?:?]
        at tc.oc.pgm.util.nms.v1_9.NMSHacks1_9.entityMetadataPacket(NMSHacks1_9.java:309) ~[?:?]
        at tc.oc.pgm.util.nms.v1_9.NMSHacks1_9.skipFireworksLaunch(NMSHacks1_9.java:319) ~[?:?]
        at tc.oc.pgm.util.nms.NMSHacks.skipFireworksLaunch(NMSHacks.java:77) ~[?:?]
        at tc.oc.pgm.destroyable.Destroyable.handleBlockChange(Destroyable.java:378) ~[?:?]
        at tc.oc.pgm.destroyable.DestroyableMatchModule.handleBlockChange(DestroyableMatchModule.java:99) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor384.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-657]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-657]
        at tc.oc.pgm.util.bukkit.Events.callEvent(Events.java:40) ~[?:?]
        at tc.oc.pgm.listeners.BlockTransformListener$1.execute(BlockTransformListener.java:138) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:299) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:226) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1285) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-657]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-657]
        at java.lang.Thread.run(Thread.java:835) [?:?]

**Comment by chatasma** [comment]
Issue appearing to happen when PGM tries to set the lifetime of the destroyable fireworks to be short. Looks like some bad reflection call in the NBT library that tries to set the lifetime, avoided this altogether by just using standard API to set the firework lifetime.
