### ISSUE TITLE
HangingBreakByEntityEvent Bug

### ISSUE THREAD

**Issue by Mew2K** [chatasma/PGM#8]
**Issue Description**: Breaking an empty item frame or painting by left-clicking on it, shooting an arrow at it, or causing a creeper explosion near it will cause a similar variation of this error message to be outputted to the console (all variations still make reference to HangingBreakByEntityEvent; the only difference is that the stack-trace will reference what specifically caused the empty-item-frame/painting to break depending on if you left-clicked, shot an error, or exploded a creeper). Using tnt to break these objects does not throw the error (tnt is utilized on this map as an item in the kits system). The empty-item-frame/painting item will drop and can be picked up when broken in all cases (however, in PGM 1.8, it seems intended for these objects to drop as items when broken with tnt).

**Map**: MobArena: Silent City

**Stack Trace** (specifically from breaking an empty-item-frame by left-clicking on it):
[12:21:29 ERROR]: Could not pass event HangingBreakByEntityEvent to PGM v0.16-SNAPSHOT (git-28259e6)
java.lang.IllegalArgumentException: Material must be a block!
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockState.setType(CraftBlockState.java:126) ~[patched_1.13.2.jar:git-Paper-657]
        at tc.oc.pgm.platform.v1_13.material.MaterialData1_13.apply(MaterialData1_13.java:134) ~[?:?]
        at tc.oc.pgm.util.block.BlockStates.cloneWithMaterial(BlockStates.java:26) ~[?:?]
        at tc.oc.pgm.regions.RegionMatchModule.getHangingBlockState(RegionMatchModule.java:412) ~[?:?]
        at tc.oc.pgm.regions.RegionMatchModule.handleHangingBreak(RegionMatchModule.java:365) ~[?:?]
        at tc.oc.pgm.regions.RegionMatchModule.checkHangingBreak(RegionMatchModule.java:290) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor228.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-657]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.EntityHanging.damageEntity(EntityHanging.java:178) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.EntityItemFrame.damageEntity(EntityItemFrame.java:109) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.EntityHanging.t(EntityHanging.java:158) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.EntityHuman.attack(EntityHuman.java:1013) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.EntityPlayer.attack(EntityPlayer.java:1492) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2011) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-657]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-657]
        at java.lang.Thread.run(Thread.java:835) [?:?]

**Comment by chatasma** [comment]
Same resolution as #10
