### ISSUE TITLE
PlayerInteractEntityEvent Bug

### ISSUE THREAD

**Issue by Mew2K** [chatasma/PGM#9]
**Issue Description**: Interacting with an item frame by right-clicking on it (regardless of whether it is empty or not) will cause this error (or a similar variation) to be thrown to the console. However the item-frame is interacted with, it will behave like a vanilla item-frame (i.e. you can place an item in empty item-frames, rotate an item in an item-frame, etc.). In PGM 1.8, it does seem intended to be able to rotate the item in the item-frame though.

**Map**: MobArena: Silent City

**Stack Trace**:
[12:35:12 ERROR]: Could not pass event PlayerInteractEntityEvent to PGM v0.16-SNAPSHOT (git-28259e6)
java.lang.IllegalArgumentException: Material must be a block!
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockState.setType(CraftBlockState.java:126) ~[patched_1.13.2.jar:git-Paper-657]
        at tc.oc.pgm.platform.v1_13.material.MaterialData1_13.apply(MaterialData1_13.java:134) ~[?:?]
        at tc.oc.pgm.util.block.BlockStates.cloneWithMaterial(BlockStates.java:26) ~[?:?]
        at tc.oc.pgm.regions.RegionMatchModule.getHangingBlockState(RegionMatchModule.java:412) ~[?:?]
        at tc.oc.pgm.regions.RegionMatchModule.checkItemFrameRotate(RegionMatchModule.java:310) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor229.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-657]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1963) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-657]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-657]
        at java.lang.Thread.run(Thread.java:835) [?:?]

**Comment by chatasma** [comment]
Same resolution as #10
